export const products = [
  {
    imageUrl: "/products/athletic-cotton-socks-6-pairs.jpg",
    name: "Black and Gray Athletic Cotton Socks - 6 Pairs",
    price: 10.9,
    keywords: ["socks", "sports", "apparel"],
    category: "Footwear",
  },
  {
    imageUrl: "/products/intermediate-composite-basketball.jpg",
    name: "Intermediate Size Basketball",
    price: 20.95,
    keywords: ["sports", "basketballs"],
    category: "Category",
  },
  {
    imageUrl: "/products/adults-plain-cotton-tshirt-2-pack-teal.jpg",
    name: "Adults Plain Cotton T-Shirt - 2 Pack",
    price: 7.99,
    keywords: ["tshirts", "apparel", "mens"],
    category: "Shirt",
  },
  {
    imageUrl: "/products/black-2-slot-toaster.jpg",
    name: "2 Slot Toaster - Black",
    price: 18.99,
    keywords: ["toaster", "kitchen", "appliances"],
    category: "clothing",
  },
  {
    imageUrl: "/products/6-piece-white-dinner-plate-set.jpg",
    name: "6 Piece White Dinner Plate Set",
    price: 20.67,
    keywords: ["plates", "kitchen", "dining"],
    category: "clothing",
  },
  {
    imageUrl: "/products/6-piece-non-stick-baking-set.webp",
    name: "6-Piece Nonstick, Carbon Steel Oven Bakeware Baking Set",
    price: 34.99,
    keywords: ["kitchen", "cookware"],
    category: "clothing",
  },
  {
    imageUrl: "/products/plain-hooded-fleece-sweatshirt-yellow.jpg",
    name: "Plain Hooded Fleece Sweatshirt",
    price: 24.0,
    keywords: ["hoodies", "sweaters", "apparel"],
    category: "clothing",
  },
  {
    imageUrl: "/products/luxury-tower-set-6-piece.jpg",
    name: "Luxury Towel Set - Graphite Gray",
    price: 35.99,
    keywords: ["bathroom", "washroom", "restroom", "towels", "bath towels"],
    category: "clothing",
  },
  {
    imageUrl: "/products/liquid-laundry-detergent-plain.jpg",
    name: "Liquid Laundry Detergent, 110 Loads, 82.5 Fl Oz",
    price: 28.99,
    keywords: ["bathroom", "cleaning"],
    category: "clothing",
  },
  {
    imageUrl: "/products/knit-athletic-sneakers-gray.jpg",
    name: "Waterproof Knit Athletic Sneakers - Gray",
    price: 33.9,
    keywords: ["shoes", "running shoes", "footwear"],
    category: "clothing",
  },
  {
    imageUrl: "/products/women-chiffon-beachwear-coverup-black.jpg",
    name: "Women's Chiffon Beachwear Cover Up - Black",
    price: 20.7,
    keywords: ["robe", "swimsuit", "swimming", "bathing", "apparel"],
    category: "clothing",
  },
  {
    imageUrl: "/products/round-sunglasses-black.jpg",
    name: "Round Sunglasses",
    price: 15.6,
    keywords: ["accessories", "shades"],
    category: "clothing",
  },
  {
    imageUrl: "/products/women-beach-sandals.jpg",
    name: "Women's Two Strap Buckle Sandals - Tan",
    price: 24.99,
    keywords: ["footwear", "sandals", "womens", "beach", "summer"],
    category: "clothing",
  },
  {
    imageUrl: "/products/blackout-curtain-set-beige.webp",
    name: "Blackout Curtains Set 4-Pack - Beige",
    price: 45.99,
    keywords: ["bedroom", "curtains", "home"],
    category: "clothing",
  },
  {
    imageUrl: "/products/men-slim-fit-summer-shorts-gray.jpg",
    name: "Men's Slim-Fit Summer Shorts",
    price: 16.99,
    keywords: ["shorts", "apparel", "mens"],
    category: "clothing",
  },
  {
    imageUrl: "/products/electric-glass-and-steel-hot-water-kettle.webp",
    name: "Electric Glass and Steel Hot Tea Water Kettle - 1.7-Liter",
    price: 30.74,
    keywords: ["water boiler", "appliances", "kitchen"],
    category: "clothing",
  },
  {
    imageUrl: "/products/facial-tissue-2-ply-18-boxes.jpg",
    name: "Ultra Soft Tissue 2-Ply - 18 Box",
    price: 23.74,
    keywords: ["kleenex", "tissues", "kitchen", "tissues box", "napkins"],
    category: "clothing",
  },
  {
    imageUrl: "/products/straw-sunhat.webp",
    name: "Straw Lifeguard Sun Hat",
    price: 22.0,
    keywords: ["hats", "straw hats", "summer", "apparel"],
    category: "clothing",
  },
  {
    imageUrl: "/products/sky-flower-stud-earrings.webp",
    name: "Sterling Silver Sky Flower Stud Earrings",
    price: 17.99,
    keywords: ["jewelry", "accessories", "womens"],
    category: "clothing",
  },
  {
    imageUrl: "/products/women-stretch-popover-hoodie-black.jpg",
    name: "Women's Stretch Popover Hoodie",
    price: 13.74,
    keywords: ["hooded", "hoodies", "sweaters", "womens", "apparel"],
    category: "clothing",
  },
  {
    imageUrl: "/products/bathroom-rug.jpg",
    name: "Bathroom Bath Rug Mat 20 x 31 Inch - Grey",
    price: 12.5,
    keywords: ["bathmat", "bathroom", "home"],
    category: "clothing",
  },
  {
    imageUrl: "/products/women-knit-ballet-flat-black.jpg",
    name: "Women's Knit Ballet Flat",
    price: 26.4,
    keywords: ["shoes", "flats", "womens", "footwear"],
    category: "clothing",
  },
  {
    imageUrl: "/products/men-golf-polo-t-shirt-blue.jpg",
    name: "Men's Regular-Fit Quick-Dry Golf Polo Shirt",
    price: 15.99,
    keywords: ["tshirts", "shirts", "apparel", "mens"],
    category: "clothing",
  },
  {
    imageUrl: "/products/trash-can-with-foot-pedal-50-liter.jpg",
    name: "Trash Can with Foot Pedal - Brushed Stainless Steel",
    price: 83.0,
    keywords: ["garbage", "bins", "cans", "kitchen"],
    category: "clothing",
  },
  {
    imageUrl: "/products/duvet-cover-set-blue-twin.jpg",
    name: "Duvet Cover Set with Zipper Closure",
    price: 23.99,
    keywords: ["bedroom", "bed sheets", "sheets", "covers", "home"],
    category: "clothing",
  },
  {
    imageUrl: "/products/women-chunky-beanie-gray.webp",
    name: "Women's Chunky Cable Beanie - Gray",
    price: 12.5,
    keywords: ["hats", "winter hats", "beanies", "tuques", "apparel", "womens"],
    category: "clothing",
  },
  {
    imageUrl: "/products/men-chino-pants-beige.jpg",
    name: "Men's Classic-fit Pleated Chino Pants",
    price: 22.9,
    keywords: ["pants", "apparel", "mens"],
    category: "clothing",
  },
  {
    imageUrl: "/products/men-athletic-shoes-green.jpg",
    name: "Men's Athletic Sneaker",
    price: 38.9,
    keywords: ["shoes", "running shoes", "footwear", "mens"],
    category: "clothing",
  },
  {
    imageUrl: "/products/men-navigator-sunglasses-brown.jpg",
    name: "Men's Navigator Sunglasses Pilot",
    price: 16.9,
    keywords: ["sunglasses", "glasses", "accessories", "shades"],
    category: "clothing",
  },
  {
    imageUrl: "/products/non-stick-cooking-set-15-pieces.webp",
    name: "Non-Stick Cookware Set, Pots, Pans and Utensils - 15 Pieces",
    price: 67.97,
    keywords: ["cooking set", "kitchen"],
    category: "clothing",
  },
  {
    imageUrl: "/products/vanity-mirror-silver.jpg",
    name: "Vanity Mirror with Heavy Base - Chrome",
    price: 16.49,
    keywords: ["bathroom", "washroom", "mirrors", "home"],
    category: "clothing",
  },
  {
    imageUrl: "/products/women-french-terry-fleece-jogger-camo.jpg",
    name: "Women's Fleece Jogger Sweatpant",
    price: 24.0,
    keywords: ["pants", "sweatpants", "jogging", "apparel", "womens"],
    category: "clothing",
  },
  {
    imageUrl: "/products/double-elongated-twist-french-wire-earrings.webp",
    name: "Double Oval Twist French Wire Earrings - Gold",
    price: 24.0,
    keywords: ["accessories", "womens"],
    category: "clothing",
  },
  {
    imageUrl: "/products/round-airtight-food-storage-containers.jpg",
    name: "Round Airtight Food Storage Containers - 5 Piece",
    price: 28.99,
    keywords: ["boxes", "food containers", "kitchen"],
    category: "clothing",
  },
  {
    imageUrl: "/products/coffeemaker-with-glass-carafe-black.jpg",
    name: "Coffeemaker with Glass Carafe and Reusable Filter - 25 Oz, Black",
    price: 22.5,
    keywords: ["coffeemakers", "kitchen", "appliances"],
    category: "clothing",
  },
  {
    imageUrl: "/products/blackout-curtains-black.jpg",
    name: "Blackout Curtains Set 42 x 84-Inch - Black, 2 Panels",
    price: 30.99,
    keywords: ["bedroom", "home"],
    category: "clothing",
  },
  {
    imageUrl: "/products/cotton-bath-towels-teal.webp",
    name: "100% Cotton Bath Towels - 2 Pack, Light Teal",
    price: 21.1,
    keywords: ["bathroom", "home", "towels"],
    category: "clothing",
  },
  {
    imageUrl: "/products/knit-athletic-sneakers-pink.webp",
    name: "Waterproof Knit Athletic Sneakers - Pink",
    price: 33.9,
    keywords: ["shoes", "running shoes", "footwear", "womens"],
    category: "clothing",
  },
  {
    imageUrl: "/products/countertop-blender-64-oz.jpg",
    name: "Countertop Blender - 64oz, 1400 Watts",
    price: 107.47,
    keywords: ["food blenders", "kitchen", "appliances"],
    category: "clothing",
  },
  {
    imageUrl: "/products/floral-mixing-bowl-set.jpg",
    name: "10-Piece Mixing Bowl Set with Lids - Floral",
    price: 38.99,
    keywords: ["mixing bowls", "baking", "cookware", "kitchen"],
    category: "clothing",
  },
  {
    imageUrl: "/products/kitchen-paper-towels-30-pack.jpg",
    name: "2-Ply Kitchen Paper Towels - 30 Pack",
    price: 57.99,
    keywords: ["kitchen", "kitchen towels", "tissues"],
    category: "clothing",
  },
  {
    imageUrl: "/products/men-cozy-fleece-zip-up-hoodie-red.jpg",
    name: "Men's Full-Zip Hooded Fleece Sweatshirt",
    price: 24.0,
    keywords: ["sweaters", "hoodies", "apparel", "mens"],
    category: "clothing",
  },
];
